### ISSUE TITLE
Decouple design from controller

### ISSUE THREAD

**Issue by Messj1** [FriendsOfTYPO3/frontend_editing#488]
Hi

As part of improve code quality #432 and to improve extend ability there should be more separation of design and frontend-editing functionality.

I see following wrong dependencies flow:
- FrontendEditing -> own iframe
FrontendEditing should use FrontendEditing.GUI since it is part of an process and GUI is the controller
- FrontendEditing.GUI -> HTML Element
FrontendEditing.GUI has to be simply a controller. So no animation at all since it can not know the template.

In my opinion we should not attache events on server generated templates.
The frontend editing GUI appearance should be part of the design or else you can only change color :unamused:

## So what should GUI be?

It is used as
- Controller
Initialize frontend editing an configure them
- HTML data binding
Of courseGUI has to deal with data but in a predefined way configurable with identifiers

So it has to contain only bootstrap code and  base composition logic code

## What should be part of design
Everything that is generated on the server. So if it has to communicate we have to use `id` attribute because it should be unique or else it is to unclear what to do in GUI.

So as a good example lets have look at a simple slide and open problem.

### checkbox hack

So we could use a good old classic hack to save and transfer the state (usable in GUI with `t3-frontend-editing__right-bar` as id)
```CSS
#t3-frontend-editing__right-bar + .t3-frontend-editing__right-bar {
    transition: right 0.2s linear;
}

#t3-frontend-editing__right-bar:checked + .t3-frontend-editing__right-bar {
    right: 0;
}

#t3-frontend-editing__right-bar:checked + .t3-frontend-editing__right-bar .top-right-title .right-bar-button {
    left: 0;
}
```
```HTML
<input type="checkbox" id="t3-frontend-editing__right-bar--open"/>
<div class="t3-frontend-editing__right-bar">
  <div class="top-right-bar-wrapper ">
    <div class="top-right-relative">
      <div class="top-right-title">
        <label for="t3-frontend-editing__right-bar--open" class="right-bar-button icons icon-icons-arrow-double"></label>
        ...
      </div>
      ...
    </div>
    ...
  </div>
</div>
```
Also possible to use radio instead of checkbox to get an real accordion :wink: 

### `details` and `summary` elements

Good old `details` elements have the advanced, that the have an `open` attribute which indicate open or close.
```CSS
details[open] .icon-icons-arrow-down:before {
    content: "\e90f";
}
```
```HTML
<details open>
  <summary class="accordion">
    ...
    <div class="element-action">
      ...
      <span class="icons icon-icons-arrow-down trigger"></span>
    </div>
  </summary>
  <div class="accordion-content">
  ...
  </div>
</details>
```

### separate javascript based widgets

There are plenty technologies for js based widgets.
From Web Components to attached function calls.
From scripts to suits.

## Conclusion

GUI should have different strategies to fetch data from the attached bindings like:

- `checked` attribut
- `selected` attribut
- `data` attribut
 - `open` attribut
- and mybe more

At least there should be the opportunity to write an own editor and use only the base logic from frontend editing to transfer and handle data.
I would love to see an different frontend editing GUI implementation.

Any opinions?
